import { useState } from 'react'
import { GEMINI_IMAGE_MODELS } from '../data/geminiModels'

interface Props {
  apiKey: string
  onApiKeyChange: (key: string) => void
  modelId: string
  onModelChange: (id: string) => void
}

export function ApiKeyInput({ apiKey, onApiKeyChange, modelId, onModelChange }: Props) {
  const [reveal, setReveal] = useState(false)

  return (
    <section className="card">
      <h2>1. Connect your Gemini API key</h2>
      <p className="hint">
        Wrap art is generated by Google's Gemini image models (Claude doesn't generate images). Get a free key at{' '}
        <a href="https://aistudio.google.com/apikey" target="_blank" rel="noreferrer">
          aistudio.google.com/apikey
        </a>
        . The key stays in your browser's local storage and is only sent directly to Google's API — never to any
        server of ours. Because this is a client-only app, avoid deploying it publicly with your key exposed.
      </p>
      <div className="row">
        <label className="field">
          <span>API key</span>
          <div className="key-input">
            <input
              type={reveal ? 'text' : 'password'}
              value={apiKey}
              onChange={(e) => onApiKeyChange(e.target.value)}
              placeholder="AIza..."
              autoComplete="off"
            />
            <button type="button" className="ghost-btn" onClick={() => setReveal((r) => !r)}>
              {reveal ? 'Hide' : 'Show'}
            </button>
          </div>
        </label>
        <label className="field">
          <span>Model</span>
          <select value={modelId} onChange={(e) => onModelChange(e.target.value)}>
            {GEMINI_IMAGE_MODELS.map((m) => (
              <option key={m.id} value={m.id} title={m.description}>
                {m.label}
              </option>
            ))}
          </select>
        </label>
      </div>
    </section>
  )
}
